(function(){var c,f;typeof ac_info_ware==="undefined"&&(ac_info_ware={});f=ac_info_ware;(function(){var k=navigator.userAgent.toLowerCase(),l=k.indexOf("like mac os x")!=-1?!0:!1;typeof _acW!=="undefined"?c=_acW:(c=_acW={getProtocol:function(){return"http://"},joinParameters:function(a,b){var d=[];if(b===",")for(var c in a)a.hasOwnProperty(c)&&Array.prototype.push.call(d,a[c]);else if(b==="&")for(var h in a)a.hasOwnProperty(h)&&Array.prototype.push.call(d,h+"="+a[h]);return d.join(b)},createCacheBuster:function(){return Math.ceil(Math.random()*
1E10)},getCookieEnabled:function(){return navigator.cookieEnabled?1:0},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(b){}return encodeURIComponent(a)},getCurrentUrl:function(){var a="";try{a=top.location.href}catch(b){try{a=document.referrer}catch(d){}}return encodeURIComponent(a)},getCharset:function(){var a="";(a=document.charset?document.charset:document.characterSet)||(a="utf-8");return a=a.toLowerCase()},load:function(a,b,d,c,h){var e,f=/loaded|complete/i,i="ac_script_$"+
Math.ceil(Math.random()*1E10),j=document.getElementsByTagName("script"),j=document.body?document.body.firstChild:j[0];b?(e=document.createElement("script"),e.type="text/javascript",e.async=1,e.id=i,e.src=a,j.parentNode.insertBefore(e,j)):(typeof ActiveXObject!=="undefined"&&(f=/complete/i),document.write('<script type="text/javascript" src="'+a+'" id="'+i+'"><\/script>'));if(e=document.getElementById(i))e.onload=e.onreadystatechange=function(){if(!e.readyState||e.readyState.match(f))if(typeof d===
"function"&&(d(),d=null),e&&e.parentNode)e.onload=e.onreadystatechange=null,e.parentNode.removeChild(e),e=null};c&&setTimeout(function(){if(e)typeof h==="function"&&(h(),h=null),e.src="javascript:void(0)"},c)},send:function(a,b){var d,g=document.getElementsByTagName("script")[0];d=/\[timestamp\]|\[ts\]/i;var h=/\[vid\]/i,b=b?b:Math.ceil(Math.random()*1E8);if(a){a=a.replace(h,c.vid?c.vid:"");if(d.test(a)){if(!f.ts)f.ts=new Date-0;a=a.replace(d,f.ts)}else a+=a.indexOf("?")!=-1?"&cb="+b:"?cb="+b;d=document.createElement("img");
d.style.display="none";g.parentNode.insertBefore(d,g);d.src=a}},track:function(a){for(var a=a.split("|||"),b=0;b<a.length;b++)a[b]&&c.send(a[b])},$:function(a){return typeof a=="string"?document.getElementById(a):a},css:function(a,b){var d=c.$(a);if(typeof b=="string"){if(d.currentStyle)return d.currentStyle[b];if(window.getComputedStyle)return document.defaultView.getComputedStyle(d,null)[b]}else if(typeof b=="object")for(var g in b)b.hasOwnProperty(g)&&(d.style[g]=b[g])},element:function(a,b,d,
g){a=document.createElement(a);if(b)for(var h in b)b.hasOwnProperty(h)&&a.setAttribute(h,b[h]);d&&c.css(a,d);if(g)a.innerHTML=g;return a},getVPSize:function(){return[document.compatMode=="CSS1Compat"?document.documentElement.clientWidth:document.body.clientWidth,document.compatMode=="CSS1Compat"?document.documentElement.clientHeight:document.body.clientHeight]},postMessage:function(a,b,d){var c="ch"+Math.ceil(Math.random()*1E8);b.chid=c;b.sender="csbew";d&&(f[c]=d);a.postMessage(b,"*")},addEvent:function(a,
b,d){a.attachEvent?a.attachEvent("on"+b,d):a.addEventListener&&a.addEventListener(b,d,!1)},removeEvent:function(a,b,d){a.detachEvent?a.detachEvent("on"+b,d):a.removeEventListener&&a.removeEventListener(b,d,!1)},apply:function(a,b,d){d&&this.apply(a,d);if(a&&b&&typeof b=="object")for(var c in b)a[c]=b[c];return a},parseScript:function(a){for(var b=a.getElementsByTagName("script"),d=function(a,b){for(var d=0;d<b.length;d++)a.setAttributeNode(b[d].cloneNode(!1))},c,h,e=0;e<b.length;e++){c=b[e];h=document.createElement("script");
d(h,c.attributes);if(c.textContent!="")h.textContent=c.textContent;a.replaceChild(h,c)}},ifmcode:function(a,b,d,g){var h,e="",f,i=Math.ceil(Math.random()*1E6),a={id:a+i,name:a+i,src:"about:blank",width:d,height:g,vspace:"0",hspace:"0",allowTransparency:"true",scrolling:"no",marginHeight:"0",marginWidth:"0",frameBorder:"0",align:"center,center"},j=!(window.opera||k.indexOf("msie")!=-1),l=function(a){for(var b=document.getElementsByTagName("base"),d=null,c=b.length;c--;)if(b[c].target&&b[c].target.toLowerCase()!==
"_self"){d=b[c];break}d?(d.setAttribute("preTarget",d.target),d.target="_self",a&&a(function(){d.target=d.getAttribute("preTarget")})):a&&a()},m=function(){l(function(a){e=e.replace(/[\'\"\/\\]/g,"\\$&");e=e.replace(/\r/g,"\\r");e=e.replace(/\n/g,"\\n");e=e.replace(/\t/g,"\\t");e="javascript:(function(){document.open('text/html','replace');document.domain=\""+document.domain+'";document.write("'+e+'");'+(j?"document.close();":"")+"})();";try{h.src=e}catch(b){}a&&a()})},e=function(a){a.indexOf("<body>")==
-1&&(a='<!doctype html><html><head><meta charset="utf-8" /><style>html,body{margin:0;padding:0;}</style></head><body>'+a+"</body></html>");return a}(b);h=c.element("iframe",a,{border:0,verticalAlign:"bottom",margin:"0 auto",display:"block",overflow:"hidden"});c.addEvent(h,"load",function(){c.removeEvent(h,"load",arguments.callee);try{f=h.contentWindow.document;try{f.open("text/html","replace"),f.write(e),j&&f.close()}catch(a){}}catch(b){k.indexOf("msie")!=-1?setTimeout(function(){m()},0):m()}});return h},
q:function(a){return new c.q.prototype.init(a)},r:function(a,b,d,g){return new c.r.prototype.init(a,b,d,g)}},c.addEvent(window,"message",function(a){var a=a.data,b=a.ctr;if(b=="ware"){var b=a.sender,d=a.chid;if(b&&b=="csbew"&&d&&f[d])f[d](a)}else if(b=="warer"&&(d=a.aid,b=a.method,a=a.params?a.params:[],d&&b&&(d=f["r"+d])&&d[b]))try{d[b].apply(d,a)}catch(c){}},!1),c.q.prototype={init:function(a){var b=this;if(a&&a.aid)a=c.apply({},a,{async:0,sendReferer:!1,sendTopUrl:!1}),b.aid=a.aid,function(){var a=
"ac_js86_"+b.aid;if(!c.$(a)){var g=document.getElementsByTagName("script"),g=g[g.length-1],f=document.createElement("script");f.id=a;g.parentNode.insertBefore(f,g)}}(),f["i"+b.aid]=a,b.info("async")?l?(b.info("async",1),b.getCustomCookie(function(a){c.load(b.getServerUrl()+b.getParameters({cc:encodeURIComponent(a)}),b.info("async"))})):c.load(b.getServerUrl()+b.getParameters(),b.info("async")):c.load(b.getServerUrl()+b.getParameters(),b.info("async")),f["q"+b.aid]=b},info:function(a,b){var d="i"+
this.aid;typeof f==="undefined"&&(f={});f[d]||(f[d]={});typeof b!=="undefined"&&(b===null?delete f[this.aid][a]:f[d][a]=b);return f[d][a]},getParameters:function(a){var b=c.getPreviousUrl(),d=c.getCurrentUrl(),g={a:this.info("aid"),ce:c.getCookieEnabled(),ec:c.getCharset(),sr:screen.width+","+screen.height,vps:c.getVPSize().join(",")};a&&c.apply(g,a);if(this.info("sendReferer")&&b!=="")g.purl=b;if(this.info("sendTopUrl")&&d!==""&&d!=encodeURIComponent(location.href))g.curl=d;if(this.info("sendkeywords")==
1&&typeof window.ac_keywords_targeting!=="undefined"&&ac_keywords_targeting)try{g.kw=encodeURIComponent(ac_keywords_targeting)}catch(f){}if(typeof window.ac_content_targeting!=="undefined"&&ac_content_targeting)try{g.ct=encodeURIComponent(ac_content_targeting)}catch(e){}if(typeof window.ac_content_id!=="undefined"&&ac_content_id)try{g.ctid=encodeURIComponent(ac_content_id)}catch(k){}if(!g.cb)g.cb=[new Date-0,Math.floor((Math.random()+1)*1E4)].join("");if(window.localStorage)try{if(localStorage._asp_cookie)g.cc=
this.getFirstCookie()}catch(i){}return c.joinParameters(g,"&")},getFirstCookie:function(){var a=JSON.parse(localStorage._asp_cookie),b=new Date-0,d=[],c;for(c in a)a[c][1]>b&&d.push(c+"="+a[c]);return encodeURIComponent(d.join(","))},getCustomCookie:function(a){var b=c.element("iframe",{src:""},{display:"none"});b.src=c.getProtocol()+this.getStaticUrl()+"ls.htm";c.addEvent(b,"load",function(){c.removeEvent(b,"load",arguments.callee);c.postMessage(b.contentWindow,{ctr:"getCookie"},function(b){a(b.cc)})});
document.body.insertBefore(b,document.body.firstChild);this.info("lcbridge",b)},getServerUrl:function(){return c.getProtocol()+this.getBaseUrl()+"s.htm?"},getBaseUrl:function(){return this.info("serverbaseurl")?this.info("serverbaseurl"):this.getLBUrl()},getLBUrl:function(){return this.info("serverbaseurl","csbew.com/")},getStaticUrl:function(){return this.info("staticbaseurl")?this.info("staticbaseurl"):this.info("staticbaseurl","s.csbew.com/")}},c.q.prototype.init.prototype=c.q.prototype,c.r.prototype=
{init:function(a){var b=this;if(a.mid){b.aid=a.aid;b.mid=a.mid;b.cid=a.cid;b.o=a;if(a.vid)c.vid=a.vid;if(a.cc)if(b.info("lcbridge"))try{c.postMessage(b.info("lcbridge").contentWindow,{ctr:"setCookie",cc:a.cc})}catch(d){}else try{if(window.localStorage&&localStorage._asp_cookie){var g=JSON.parse(localStorage._asp_cookie);c.apply(g,a.cc);localStorage._asp_cookie=JSON.stringify(g)}}catch(h){}if(a.type==1){if(b.creative=c.element("img",{src:a.data,border:0,alt:""},{width:"100%"}),a.cu&&a.cu!="")b.creative.onclick=
function(){a.cu&&window.open(a.cu);b.sendClickReport()}}else if(a.type==2)a.data.indexOf("#")==-1?a.data+="#":a.data=a.data.replace(/(?:#).+/,""),a.data+=c.joinParameters({aid:a.aid,clk:encodeURIComponent(a.cu),curl:c.getCurrentUrl(),purl:c.getPreviousUrl()},"&"),b.creative=c.element("iframe",{width:a.w,height:a.h,src:a.data,frameBorder:0,scrolling:"no"});else{if(a.at==1)b.creative=c.element("ins",null,{display:"block",padding:"0",margin:"0 auto","text-decoration":"none"},a.data),c.parseScript(b.creative);
a.at==2?document.write(a.data):(a.data="<script>var _maxCount = 50, _aid = "+a.aid+';function _ifmResize(){parent.postMessage({method:"setSize",ctr:"warer",aid: _aid,params:[{"height":document.body.clientHeight+"px"}]},"*");};window.addEventListener("DOMContentLoaded",function(){if(_maxCount>=0){_maxCount--;_ifmResize();setTimeout(arguments.callee,200)}},false); var MutationObserver = window.MutationObserver || window.WebKitMutationObserver || window.MozMutationObserver; if(!!MutationObserver){ var mo = new MutationObserver(function(){_ifmResize();});mo.observe(document.body, {"childList": true,"subtree": true});} <\/script>'+
a.data,b.creative=c.element("ins",null,{display:"block",overflow:"hidden",height:"50px",width:"100%",padding:"0",margin:"0 auto","text-decoration":"none"}),b.codeIfm=c.ifmcode("ac_js86_cr"+a.aid,a.data,"100%",document.documentElement.clientHeight),b.creative.appendChild(b.codeIfm))}b.creative&&b.append(b.creative);a.itu&&c.track(a.itu);f["r"+b.aid]=b}else typeof b.info("ad_none")==="function"?b.info("ad_none")():typeof b.info("noAd")==="function"&&b.info("noAd")(aid)},info:function(a,b){var c="i"+
this.aid;typeof f=="undefined"&&(f={});f[c]||(f[c]={});typeof b!="undefined"&&(b===null?delete f[c][a]:f[c][a]=b);return f[c][a]},setSize:function(a){for(var b in a)a.hasOwnProperty(b)&&(this.creative.style[b]=a[b],this.creative[b]=a[b].replace(/[^0-9%]+/g,""))},append:function(a){var b=this.info("destid"),d;if(b&&c.$(b))c.$(b).appendChild(a);else if(b=c.$("ac_js86_"+this.aid))(d=b.parentNode)&&d.insertBefore(a,b)},sendClickReport:function(){var a=this.o;a.ctu&&c.track(a.ctu);this.report(1)},report:function(a){a=
{pv:1,sp:[this.aid,this.mid,this.cid,a,0,0,0].join(",")};if(this.mid!=0){if(typeof window.ac_content_id=="string"&&ac_content_id!="")try{a.ctid=encodeURIComponent(ac_content_id)}catch(b){}if(this.o.vid)a.vid=this.o.vid;c.send(this.getServerUrl()+c.joinParameters(a,"&"))}},getServerUrl:function(){return c.getProtocol()+this.getBaseUrl()+"v.htm?"},getBaseUrl:function(){return this.info("serverbaseurl")?this.info("serverbaseurl"):this.getLBUrl()},getLBUrl:function(){return this.info("serverbaseurl",
"csbew.com/")}},c.r.prototype.init.prototype=c.r.prototype)})();typeof ac_as_info!="undefined"&&ac_as_info.aid&&c.q(ac_as_info)})();
