package com.manage.core;

import java.util.Hashtable;

public final class AppConstants
{
  public static final String PRI_BUILDNEWUSER = "BuildNewUser";
  public static final String PRI_BUILDNEWUSER_SHOW = "BuildNewUser_Show";
  public static final String PRI_BUILDNEWUSER_NEW = "BuildNewUser_New";
  public static final String PRI_BUILDNEWUSER_MODIFY = "BuildNewUser_Modify";
  public static final String PRI_BUILDNEWUSER_ROLE = "BuildNewUser_Role";
  public static final String PRI_PROJECT_MANAGER = "ProjectManager";
  public static final String PRI_PROJECT_MANAGER_NEW = "ProjectManager_New";
  public static final String PRI_PROJECT_MANAGER_STATUS = "ProjectManager_Status";
  public static final String PRI_PROJECT_MANAGER_FUNCTION = "ProjectManager_Function";
  public static final String PRI_PROJECT_MANAGER_FIELD = "ProjectManager_Field";
  public static final String PRI_PROJECT_MANAGER_FLOW = "ProjectManager_Flow";
  public static final String PRI_PROJECT_MANAGER_BMSTYLE = "ProjectManager_BMStyle";
  public static final String PRI_PROJECT_MANAGER_CODE = "ProjectManager_Code";
  public static final String PRI_PROJECT_MANAGER_TEMPLATE = "ProjectManager_Template";
  public static final String PRI_PROJECT_MANAGER_NBT = "ProjectManager_NBT";
  public static final String PRI_PRISETTING = "PriSetting";
  public static final String PRI_PRISETTING_SHOW = "PriSetting_Show";
  public static final String PRI_PRISETTING_NEW = "PriSetting_New";
  public static final String PRI_PRISETTING_DELETE = "PriSetting_Delete";
  public static final String PRI_ORG_MANAGER = "OrgManager";
  public static final String PRI_ORG_MANAGER_LOCAL = "OrgManager_Local";
  public static final String PRI_ORG_MANAGER_SHOW = "OrgManager_Show";
  public static final String PRI_ORG_MANAGER_ADD = "OrgManager_Add";
  public static final String PRI_ORG_MANAGER_MODIFY = "OrgManager_Modify";
  public static final String PRI_ORG_MANAGER_ACTIVE = "OrgManager_Active";
  public static final String PRI_ORG_MANAGER_DELETE = "OrgManager_Delete";
  public static final String PRI_ORG_MANAGER_BIMPROT = "OrgManager_BImprot";
  public static final String PRI_ORG_MANAGER_BEXPORT = "OrgManager_BExport";
  public static final String PRI_PLAN_MANAGER = "PlanManager";
  public static final String PRI_PLAN_MANAGER_SHOW = "PlanManager_Show";
  public static final String PRI_PLAN_MANAGER_NEW = "PlanManager_New";
  public static final String PRI_PLAN_MANAGER_MODIFY = "PlanManager_Modify";
  public static final String PRI_PLAN_MANAGER_DELETE = "PlanManager_Delete";
  public static final String PRI_PLAN_MANAGER_ACTIVE = "PlanManager_Active";
  public static final String PRI_BM_MANAGER = "BMManager";
  public static final String PRI_BM_MANAGER_LOCAL = "BMManager_Local";
  public static final String PRI_BM_MANAGER_SHOW = "BMManager_Show";
  public static final String PRI_BM_MANAGER_MODIFY = "BMManager_Modify";
  public static final String PRI_BM_MANAGER_DELETE = "BMManager_Delete";
  public static final String PRI_BM_MANAGER_BIMPORT = "BMManager_BImport";
  public static final String PRI_BM_MANAGER_BEXPORT = "BMManager_BExport";
  public static final String PRI_BM_MANAGER_MODIFYPAY = "BMManager_ModifyPay";
  public static final String PRI_BM_MANAGER_BLACKLIST = "BMManager_BlackList";
  public static final String PRI_BM_MANAGER_DELBLACKLIST = "BMManager_DelBlackList";
  public static final String PRI_ARR_MANAGER = "ArrManager";
  public static final String PRI_ARR_MANAGER_ARR = "ArrManager_Arr";
  public static final String PRI_ARR_MANAGER_EXPORT = "ArrManager_Export";
  public static final String PRI_ARR_MANAGER_EROOM = "ArrManager_ERoom";
  public static final String PRI_ARR_MANAGER_BATCHGENE = "ArrManager_BatchGene";
  public static final String PRI_ARR_MANAGER_PZ = "ArrManager_PZ";
  public static final String PRI_SCORE_MANAGER = "ScoreManager";
  public static final String PRI_SCORE_MANAGER_LOCAL = "ScoreManager_Local";
  public static final String PRI_SCORE_MANAGER_SHOW = "ScoreManager_Show";
  public static final String PRI_SCORE_MANAGER_EXPORT = "ScoreManager_Export";
  public static final String PRI_SCORE_MANAGER_IMPORT = "ScoreManager_Import";
  public static final String PRI_SCORE_MANAGER_SHENBAO = "ScoreManager_ShenBao";
  public static final String PRI_SCORE_MANAGER_SHENPI = "ScoreManager_ShenPi";
  public static final String PRI_CERTI_MANAGER = "CertiManager";
  public static final String PRI_CERTI_MANAGER_LOCAL = "CertiManager_Local";
  public static final String PRI_CERTI_MANAGER_SHOW = "CertiManager_Show";
  public static final String PRI_CERTI_MANAGER_BEXPORT = "CertiManager_BExport";
  public static final String PRI_CERTI_MANAGER_BIMPORT = "CertiManager_BImport";
  public static final String PRI_CERTI_MANAGER_GENE = "CertiManager_Gene";
  public static final String PRI_CERTI_MANAGER_CACEL = "CertiManager_Cacel";
  public static final String PRI_CERTI_MANAGER_BGENE = "CertiManager_BGene";
  public static final String PRI_CERTI_MANAGER_BDOWNLOAD = "CertiManager_BDownLoad";
  public static final String PRI_QUALITY_MANAGER = "QualityManager";
  public static final String PRI_QUALITY_MANAGER_UPLOAD = "QualityManager_Upload";
  public static final String PRI_QUALITY_MANAGER_DOWNLOAD = "QualityManager_Download";
  public static final String PRI_QUALITY_MANAGER_DELETE = "QualityManager_Delete";
  public static final String PRI_NBT = "NBT";
  public static final String PRI_NBT_SHOWEMAIL = "NBT_ShowEmail";
  public static final String PRI_NBT_SHOWTXB = "NBT_ShowTXB";
  public static final String PRI_NBT_MODIFYTXB = "NBT_ModifyTXB";
  public static final String PRI_NBT_SENDEMAIL = "NBT_SendEmail";
  public static final String PRI_YWRECORD = "YWRecord";
  public static final String PRI_YWRECORD_SHOW = "YWRecord_Show";
  public static final String PRI_YWRECORD_DOWNLOAD = "YWRecord_DownLoad";
  public static final String ORG_TYPE_PTHL = "0";
  public static final String ORG_TYPE_HZJG = "1";
  public static final String ORG_TYPE_HZJG_YH = "2";
  public static final String ORG_TYPE_CENTER = "3";
  public static final String ORG_TYPE_CENTER_PX = "4";
  public static final String ORG_TYPE_KSZ = "5";
  public static final String ORG_TYPE_PXD = "6";
  public static final String ORG_TYPE_BMD = "7";
  public static final String ORG_TYPE_JTBM = "8";
  public static final Hashtable<String, String> TABLE_ORG_TYPE = new Hashtable();
  public static final Hashtable<String, String> TABLE_ORG_KDTYPE;
  public static final Hashtable<String, String> TABLE_JDJH_NTYPE;
  public static final String FIELD_JDJH_JNAME = "JName";
  public static final String FIELD_JDJH_PNAME = "PName";
  public static final String FIELD_JDJH_PENNAME = "PENName";
  public static final String FIELD_JDJH_ONAME = "OName";
  public static final String FIELD_JDJH_JDATE = "JDate";
  public static final String FIELD_JDJH_KSLEVEL = "KSLevel";
  public static final String FIELD_JDJH_KSTIME = "KSTime";
  public static final String FIELD_JDJH_BMORG = "BMOrg";
  public static final String FIELD_JDJH_SFZVERIFYORG = "SFZVerifyOrg";
  public static final String FIELD_JDJH_ZFORG = "ZFOrg";
  public static final String FIELD_JDJH_ZKZORG = "ZKZOrg";
  public static final String FIELD_JDJH_VALIDTIME = "ValidTime";
  public static final String FIELD_JDJH_IS_ACTIVE = "IS_ACTIVE";
  public static final String FIELD_JDJH_IS_ARRANGE_KC = "IS_arrange_KC";
  public static final String FIELD_JDJH_KSFEE = "KSFee";
  public static final String FIELD_JDJH_ISALLOWZKZ = "IsAllowZKZ";
  public static final String FIELD_JDJH_ISCHENGJI = "IsChengJi";
  public static final String FIELD_JDJH_REMARKS = "Remarks";
  public static final String FIELD_ORG_AID = "AID";
  public static final String FIELD_ORG_ONAME = "OName";
  public static final String FIELD_ORG_OADDRESS = "OAddress";
  public static final String FIELD_ORG_ADVISEWAY = "AdviseWay";
  public static final String FIELD_ORG_POSTCODE = "Postcode";
  public static final String FIELD_ORG_WEBSITE = "WebSite";
  public static final String FIELD_ORG_PERSONINCHARGE = "PersonInCharge";
  public static final String FIELD_ORG_PPHONE = "PPhone";
  public static final String FIELD_ORG_PFAX = "PFax";
  public static final String FIELD_ORG_PTEL = "PTel";
  public static final String FIELD_ORG_EMAIL = "Email";
  public static final String FIELD_ORG_OTYPE = "OType";
  public static final String FIELD_ORG_ISALLOWCREATEJDJH = "IsAllowCreateJDJH";
  public static final String FIELD_ORG_REMARKS = "Remarks";
  public static final String FIELD_ORG_KDTYPE = "KDType";
  public static final String FIELD_ORG_OCODE = "OCode";
  public static final String FIELD_ORG_LOGINNAME = "LoginName";
  public static final String FIELD_ORG_OPASSWORD = "OPassword";
  public static final String FIELD_ORG_OLEVEL = "OLevel";
  public static final String FIELD_ORG_EPAYLOGIN = "EPAYLogin";
  public static final String FIELD_ORG_EPAYFENZHANG = "EPAYFenZhang";
  public static final String FIELD_BM_SNAME = "SName";
  public static final String FIELD_BM_SNAMEPY = "SNamePY";
  public static final String FIELD_BM_IDE_TYPE = "IDE_Type";
  public static final String FIELD_BM_IDE = "IDE";
  public static final String FIELD_BM_SEX = "Sex";
  public static final String FIELD_BM_SBRITHDAY = "SBrithday";
  public static final String FIELD_BM_GUOJI = "GuoJi";
  public static final String FIELD_BM_NATION = "Nation";
  public static final String FIELD_BM_SDEGREE = "SDegree";
  public static final String FIELD_BM_SWORK = "SWork";
  public static final String FIELD_BM_ORGID = "OrgID";
  public static final String FIELD_BM_ISFAPIAO = "IsFaPiao";
  public static final String FIELD_BM_ISFAPIAOTT = "IsFaPiaoTT";
  public static final String FIELD_BM_SPIC = "SPIC";
  public static final String FIELD_ARR_TIME = "time";
  public static final String FIELD_ARR_DEFAULTVALUE = "defaultValue";
  public static final String FIELD_ARR_AREACODE = "AreaCode";
  public static final String FIELD_ARR_BATCHNUMBER = "BatchNumber";
  public static final String FIELD_KEY_JH = "JH";
  public static final String FIELD_KEY_JG = "JG";
  public static final String FIELD_KEY_BM = "BM";
  public static final String FIELD_KEY_BM_ADDFILED = "BMADDFILED";
  public static final String FIELD_KEY_JG_ADDFILED = "JGADDFILED";
  public static final String FIELD_KEY_BMC = "BMC";
  public static final String FIELD_HTMLTYPE_WENBEN = "文本框";
  public static final String FIELD_HTMLTYPE_RIQI = "日期";
  public static final String FIELD_HTMLTYPE_DUOXUAN = "多选框";
  public static final String FIELD_HTMLTYPE_XIALA = "下拉框";
  public static final String FIELD_HTMLTYPE_DANXUAN = "单选框";
  public static final Hashtable<Integer, String> TABLE_FIELD_HTMLTYPE;
  public static final String FLOW_EXAM_REGISTER = "flow_exam_register";
  public static final String FLOW_SELF_DEFINITION = "flow_self_definition";
  public static final String FLOW_PAYMENT = "flow_payment";
  public static final String FLOW_ONLINE_VERYFY = "flow_online_veryfy";
  public static final String FLOW_ONLINE_VERYFY_SUCCESS = "flow_online_veryfy_success";
  public static final String FLOW_ONLINE_VERYFY_UPLOADPIC = "flow_online_veryfy_uploadPic";
  public static final String FLOW_ONLINE_VERYFY_REFUND = "flow_online_veryfy_refund";
  public static final String FLOW_ONLINE_VERYFY_XCYZ = "flow_online_veryfy_xcyz";
  public static final String FLOW_ONLINE_VERYFY_XCYZREFUND = "flow_online_veryfy_xcyz_refund";
  public static final String FLOW_ONLINE_VERYFY_FAIL = "flow_online_veryfy_fail";
  public static final String FLOW_SITE_PAYMENT_VERYFY = "flow_site_payment_veryfy";
  public static final String FLOW_GROUP_REGISTER_FIELD_SETTING = "flow_group_register_field_setting";
  public static final String FLOW_GROUP_DOWNLOAD_REGISTER = "flow_group_download_register";
  public static final String FLOW_GROUP_UPLOAD_REGISTER = "flow_group_upload_register";
  public static final String FLOW_GROUP_UPLOAD_PIC = "flow_group_upload_pic";
  public static final String FLOW_GROUP_PIC_SETTING = "flow_group_pic_setting";
  public static final String FLOW_GROUP_UPLOAD_PIC_DESCRIPTION = "flow_group_upload_pic_description";
  public static final String FLOW_GROUP_PAYMENT = "flow_group_payment";
  public static final String FLOW_GROUP_SITE_PAY_DESCRIPTION = "flow_group_site_pay_description";
  public static final String FLOW_GROUP_BANK_TRANSFER = "flow_group_bank_transfer";
  public static final String FILEPATH_PROJECT = "project";
  public static final String FILEPATH_TEMPPROJECT = "tempProject";
  public static final String FLOW_GROUP_FIELD = "flow_group_register_field_setting";
  public static final String FLOW_GROUP_PID_SETTING = "flow_group_pic_setting";

  static
  {
    TABLE_ORG_TYPE.put("0", "普天合力机构");
    TABLE_ORG_TYPE.put("1", "合作机构");
    TABLE_ORG_TYPE.put("2", "合作机构子账号");
    TABLE_ORG_TYPE.put("3", "地方中心");
    TABLE_ORG_TYPE.put("4", "培训中心");
    TABLE_ORG_TYPE.put("5", "考试点");
    TABLE_ORG_TYPE.put("6", "培训点");
    TABLE_ORG_TYPE.put("7", "报名点");
    TABLE_ORG_TYPE.put("8", "集体报名点");

    TABLE_ORG_KDTYPE = new Hashtable();

    TABLE_ORG_KDTYPE.put("1", "个人报名点");
    TABLE_ORG_KDTYPE.put("2", "集体报名点");

    TABLE_JDJH_NTYPE = new Hashtable();

    TABLE_JDJH_NTYPE.put("1", "考试计划");
    TABLE_JDJH_NTYPE.put("2", "培训计划");
    TABLE_FIELD_HTMLTYPE = new Hashtable();
    TABLE_FIELD_HTMLTYPE.put(new Integer(1), "文本框");
    TABLE_FIELD_HTMLTYPE.put(new Integer(2), "日期框");
    TABLE_FIELD_HTMLTYPE.put(new Integer(3), "多选框");
    TABLE_FIELD_HTMLTYPE.put(new Integer(4), "下拉框");
    TABLE_FIELD_HTMLTYPE.put(new Integer(5), "单选框");
  }
}